'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';

const articles = [
  { id: '1', title: 'Top 10 Call of Duty Strategies for Beginners', slug: 'top-10-call-of-duty-strategies', content: '<h2>Master the Fundamentals of Call of Duty</h2><p>Whether you\'re just starting your Call of Duty journey or looking to improve your gameplay, mastering these 10 core strategies will significantly enhance your performance on the battlefield.</p><h3>1. Map Control & Positioning</h3><p>Understanding map layout is crucial. Learn key positions, chokepoints, and sightlines. Familiarize yourself with spawning locations and rotations to always stay ahead of your enemies.</p><h3>2. Weapon Selection Strategy</h3><p>Different weapons excel in different situations. Use close-range weapons (SMGs) indoors, assault rifles for medium range, and sniper rifles for long-distance engagements. Practice weapon recoil control.</p><h3>3. Team Communication</h3><p>Effective communication with teammates is essential. Call out enemy positions, coordinate pushes, and maintain team cohesion. Use clear, concise callouts to help your team make informed decisions.</p><h3>4. Aim and Sensitivity Settings</h3><p>Find the right sensitivity setting that allows smooth aiming and quick target acquisition. Practice in aim trainers to develop muscle memory and improve reaction times.</p><h3>5. Sound Awareness</h3><p>Footsteps, gunshots, and killstreak audio cues provide valuable information. Wear headphones and learn to identify enemy movements through audio cues to stay alert.</p><h3>6. Loadout Customization</h3><p>Tailor your loadout to your playstyle. Experiment with attachments, perks, and equipment. Create loadouts for different scenarios: aggressive rushing, defensive holding, or balanced gameplay.</p><h3>7. Game Mode Awareness</h3><p>Each game mode requires different strategies. Learn objective-based gameplay for Team Deathmatch, Domination, and Search & Destroy. Understand rotation patterns and high-value positions.</p><h3>8. Enemy Prediction</h3><p>Anticipate enemy movements based on map flow and their previous positions. Pre-aim common angles and corners where enemies are likely to appear.</p><h3>9. Killstreak Management</h3><p>Effectively use scorestreaks to turn the tide of battle. Know when to call in support or offensive streaks and coordinate with teammates to maximize their impact.</p><h3>10. Consistent Practice & Improvement</h3><p>Dedicate time to practicing regularly. Watch professional players, analyze your own gameplay, and identify areas for improvement. Consistency is key to climbing the ranks.</p><p><strong>Remember, improvement comes with dedication and practice. Start with these fundamentals, and gradually build advanced techniques as you progress. Happy gaming!</strong></p>' },
  { id: '2', title: 'Season 4 Weapon Balance Update Analysis', slug: 'season-4-weapon-balance-update', content: '<h2>Season 4 Weapon Balance Changes</h2><p>The latest Season 4 weapon balance update brings significant changes to the competitive meta. Here\'s our comprehensive analysis of what changed and how it affects your gameplay.</p><h3>Assault Rifle Nerfs</h3><p>The primary assault rifles received a 5% damage reduction across the board. This means you\'ll need more shots to eliminate opponents at medium range. Adjust your playstyle accordingly.</p><h3>SMG Buffs</h3><p>Close-range submachine guns received significant buffs with improved handling and fire rate. Indoor combat is now heavily favored toward SMG users. Consider switching to SMG-focused loadouts for close-quarters maps.</p><h3>Sniper Rifle Changes</h3><p>Snipers now have improved ADS speed and reduced flinch. This makes sniping more viable in competitive play. Practice your positioning and pre-aiming to take advantage of these buffs.</p><h3>Tactical Rifle Adjustments</h3><p>Tactical rifles received quality-of-life improvements including better accuracy and recoil control. They\'re now a solid middle ground between assault rifles and sniper rifles.</p><h3>LMG Rework</h3><p>Light machine guns have been significantly improved with faster ADS and better accuracy. They\'re now viable for holding down map positions and providing suppressive fire.</p><h3>Competitive Meta Impact</h3><p>These changes shift the competitive meta toward a more balanced approach. Professional teams are already adapting their strategies and loadout choices. Stay updated with the latest pro meta to improve your competitive gameplay.</p>' },
  { id: '3', title: 'BattleGaming May Tournament Announced', slug: 'battlegaming-may-tournament', content: '<h2>BattleGaming May Tournament 2026</h2><p>We\'re excited to announce the biggest tournament of the year with $15,000 in total prizes and exclusive rewards!</p><h3>Tournament Details</h3><p><strong>Prize Pool:</strong> $15,000</p><p><strong>Format:</strong> 4v4 Team-Based Competition</p><p><strong>Registration:</strong> May 15-25, 2026</p><p><strong>Tournament Dates:</strong> May 28 - June 4, 2026</p><h3>Prize Distribution</h3><p>1st Place: $7,500 + Premium Account Bundle</p><p>2nd Place: $4,000 + Elite Account Bundle</p><p>3rd Place: $2,000 + Pro Account Bundle</p><p>4th-8th Place: $500 each + Account Credit</p><h3>Exclusive Rewards</h3><p>All tournament participants will receive exclusive cosmetics and access to our VIP gaming community. Top performers may qualify for sponsorship opportunities with BattleGaming.</p>' },
  { id: '4', title: 'How to Improve Your KD Ratio', slug: 'improve-kd-ratio-guide', content: '<h2>Expert Guide to Improving Your KD Ratio</h2><p>Your Kill-Death ratio is a fundamental metric in Call of Duty. Here\'s how professional players improve their KD and dominate the leaderboards.</p><h3>Understanding KD Ratio</h3><p>KD ratio is calculated as total kills divided by total deaths. A 1.0 KD means you average one kill per death. Top players maintain KD ratios between 2.0-4.0+ depending on their game mode.</p><h3>Positioning is Everything</h3><p>The best way to improve KD is through smart positioning. Never run around aimlessly. Hold strong positions where you can control sight lines and predict enemy movements. Use corners and cover to your advantage.</p><h3>Map Knowledge Mastery</h3><p>Learn every aspect of the maps you play on. Know spawn points, high-traffic areas, chokepoints, and power positions. This knowledge allows you to anticipate enemy movements and plan your strategy accordingly.</p><h3>Engagement Distance Control</h3><p>Control the distance at which you engage enemies. If you\'re using an SMG, find routes through the map that force close-range engagements. With an AR, maintain medium distance where your weapon excels.</p><h3>Pre-aiming and Crosshair Placement</h3><p>Before turning a corner, already have your crosshair at head height where enemies typically appear. This gives you a massive advantage in any gunfight. Practice pre-aiming in private matches.</p><h3>Sound and Radar Usage</h3><p>Use UAVs and radar effectively. Listen for footsteps and predict enemy locations. This information helps you win engagements before they even start. Good sound awareness equals fewer deaths.</p>' },
  { id: '5', title: 'New Map Review: Arctic Base', slug: 'arctic-base-map-review', content: '<h2>Arctic Base Map Complete Guide</h2><p>The new Arctic Base map offers unique gameplay opportunities. Here\'s everything you need to know to dominate this frozen battleground.</p><h3>Map Layout Overview</h3><p>Arctic Base is a medium-sized map with distinct areas: the North Base, South Base, Central Courtyard, and Underground Tunnels. Each area has unique strategic value for different playstyles.</p><h3>North Base Strategy</h3><p>The North Base features elevated positions and multiple sightlines. This area favors defensive play and long-range engagements. Control the high ground for map dominance.</p><h3>South Base Tactics</h3><p>The South Base is more compact with close-quarters combat opportunities. This area is perfect for aggressive players using SMGs and tactical equipment. Multiple entry points make it dynamic and fast-paced.</p><h3>Central Courtyard Control</h3><p>The Central Courtyard is the map\'s heart. Teams that control this area typically win matches. Use cover wisely and coordinate with teammates to secure this crucial territory.</p><h3>Underground Tunnels Strategy</h3><p>The Underground Tunnels provide shortcuts across the map but are dangerous ambush points. Use them strategically to flank enemies, but be cautious of enemy presence.</p>' },
  { id: '6', title: 'Account Security: Protecting Your Investment', slug: 'account-security-guide', content: '<h2>Complete Guide to Securing Your Gaming Account</h2><p>Your premium account is a valuable investment. Protect it with these essential security practices and tips from cybersecurity experts.</p><h3>Create a Strong Password</h3><p>Use a password that\'s at least 16 characters long, combining uppercase, lowercase, numbers, and special symbols. Avoid birthdays, common words, or predictable sequences. Use a password manager to securely store complex passwords.</p><h3>Enable Two-Factor Authentication</h3><p>2FA is your strongest defense against unauthorized access. Enable it on your gaming account, email, and password manager. Use authenticator apps rather than SMS when possible.</p><h3>Protect Your Email Address</h3><p>Your email is the key to account recovery. Use a unique, strong password for your email account. Enable 2FA on your email and avoid sharing it on public platforms.</p><h3>Recognize Phishing Attempts</h3><p>Scammers often impersonate legitimate services. Never click links in emails or Discord messages. Always navigate directly to official websites. Legitimate companies never ask for passwords via email.</p><h3>Secure Your Device</h3><p>Keep your operating system and antivirus software updated. Don\'t download files from untrusted sources or use cheats/hacks. Use a VPN when playing on public Wi-Fi networks.</p><h3>Monitor Account Activity</h3><p>Regularly check your account\'s login history and connected devices. If you see unfamiliar logins or locations, immediately change your password and contact support.</p>' },
  { id: '7', title: 'Best Premium Accounts for Competitive Play May 2026', slug: 'best-premium-accounts-competitive-play', content: '<h2>Top Tier Premium Accounts for Competitive Gaming</h2><p>Competing at the highest level requires more than skill—you need a premium account with the right stats and progression. Here are the best premium accounts currently available.</p><h3>Why Choose Premium Accounts?</h3><p>Premium accounts give you immediate access to high-level ranked play, competitive cosmetics, and established stats. They save hundreds of hours of grinding while providing credibility in the competitive community.</p><h3>Elite Pro Accounts</h3><p>Our Elite Pro tier features accounts with 2.5+ KD ratios and 500+ competitive wins. These accounts come with exclusive operator skins and are verified for authenticity. Perfect for serious competitive players.</p><h3>Master Rank Accounts</h3><p>Master Rank accounts represent the top 0.5% of players. They feature 3.0+ KD ratios, multiple seasonal awards, and complete cosmetic collections. These are the gold standard for competitive play.</p><h3>Tournament-Ready Bundles</h3><p>For tournament participation, we offer tournament-ready bundles that include verified ranking, clean history, and competitive certifications. All accounts are tournament-legal and verified.</p><h3>Authentication & Guarantees</h3><p>All premium accounts come with lifetime authentication support and a 30-day satisfaction guarantee. If you\'re not satisfied, we offer account swaps or full refunds.</p><h3>How to Get Started</h3><p>Browse our competitive accounts, read customer reviews, and select your perfect match. Our support team handles instant delivery and account transfer securely and efficiently.</p>' },
  { id: '8', title: 'Cross-Platform Gaming Guide: Play on Any Device', slug: 'cross-platform-gaming-guide', content: '<h2>Complete Cross-Platform Gaming Guide</h2><p>Call of Duty supports seamless cross-platform play. Here\'s how to set up and optimize your cross-platform gaming experience across PS5, Xbox, and PC.</p><h3>Cross-Platform Progression Explained</h3><p>Your Activision account links all your gaming platforms. Progress, cosmetics, and rank automatically sync across PS5, Xbox Series X/S, and PC. Switch platforms anytime without losing progress.</p><h3>Setting Up Your Activision Account</h3><p>Create or link your Activision account on the official website. Use the same email for all platforms. This single account becomes your universal gaming identity across all devices.</p><h3>PS5 Setup Guide</h3><p>Download Call of Duty from PlayStation Store, launch the game, and link your Activision account at startup. Your PlayStation Network account automatically connects to your Activision profile.</p><h3>Xbox Setup Guide</h3><p>Download from Xbox Game Pass or Microsoft Store, launch the game, and sign in with your Xbox Live account. Your Game Pass membership provides instant access to the full game.</p><h3>PC Setup Guide</h3><p>Download from Battle.net, launch the game, and link your Battle.net account to your Activision account. PC offers the highest graphical fidelity and competitive performance options.</p><h3>Performance Comparison</h3><p>PC offers the best graphical performance and highest frame rates. PS5 and Xbox Series X provide consistent 120fps. Choose based on your preferences for graphics versus competitive advantage.</p>' },
];

export default function ArticlesPage() {
  const params = useParams();
  const articleSlug = params?.slug?.[0];

  const article = articles.find(a => a.slug === articleSlug);

  if (!article) {
    return (
      <div className="bg-[#0d071a] min-h-screen text-white">
        <div className="max-w-4xl mx-auto py-12 px-4">
          <h1 className="text-4xl font-bold text-[#FF7828] mb-8">Article Not Found</h1>
          <Link href="/news" className="text-[#FF7828] hover:underline">
            ← Back to News
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-[#0d071a] min-h-screen text-white">
      <style>{`
        .article-content h2 {
          font-size: 1.875rem;
          font-weight: bold;
          color: #FF7828;
          margin-top: 1.5rem;
          margin-bottom: 1rem;
        }
        .article-content h3 {
          font-size: 1.25rem;
          font-weight: bold;
          color: #FFB366;
          margin-top: 1.25rem;
          margin-bottom: 0.75rem;
        }
        .article-content p {
          margin-bottom: 1rem;
          line-height: 1.75;
          color: #e5e7eb;
        }
        .article-content strong {
          color: #FF7828;
        }
      `}</style>
      <div className="max-w-4xl mx-auto py-12 px-4">
        <h1 className="text-4xl font-bold mb-8 text-[#FF7828]">{article.title}</h1>
        <div className="article-content mb-8" dangerouslySetInnerHTML={{ __html: article.content }} />
        <Link href="/news" className="text-[#FF7828] hover:underline font-bold">
          ← Back to News
        </Link>
      </div>
    </div>
  );
}
